### ISSUE TITLE
Update the song_score_upload and song_score_download modules to latest versions

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/sanger-wgs-variant-calling#15]
song/score client have some fixes to address the upload/download issue:
https://github.com/icgc-argo/workflow-roadmap/issues/324
https://github.com/icgc-argo/workflow-roadmap/issues/333

The sanger workflow needs to update the modules to use the latest versions of song/score client.

**Comment by puneet-oicr** [comment]
PR created - https://github.com/icgc-argo-workflows/sanger-wgs-variant-calling/pull/16

**Comment by edsu7** [comment]
bump song_score_upload version

**Comment by lindaxiang** [comment]
PR has been merged, closing.
